import jsPDF from 'jspdf';
import type { PredictionResult, AudioFileInfo, AppSettings } from '../types';

// ─── Constants ────────────────────────────────────────────────────────────────
const COLORS = {
  bg: [3, 7, 18] as [number, number, number],
  bgCard: [10, 15, 30] as [number, number, number],
  cyan: [6, 182, 212] as [number, number, number],
  green: [16, 185, 129] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
  purple: [139, 92, 246] as [number, number, number],
  blue: [59, 130, 246] as [number, number, number],
  white: [241, 245, 249] as [number, number, number],
  muted: [71, 85, 105] as [number, number, number],
  secondary: [148, 163, 184] as [number, number, number],
  border: [30, 41, 59] as [number, number, number],
};

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

const FEATURE_DESCRIPTIONS: Record<string, string> = {
  mel: 'Mel-scaled frequency representation of speech energy distribution.',
  mfcc: 'Mel Frequency Cepstral Coefficients for vocal characteristic analysis.',
  spectrogram: 'Frequency content over time revealing speech structure.',
  chroma: 'Harmonic pitch class distribution for tonal analysis.',
  spectral_contrast: 'Spectral peak-valley difference for acoustic texture.',
  rir: 'Room Impulse Response for environmental consistency detection.',
};

// ─── Drawing Helpers ──────────────────────────────────────────────────────────
function setFill(doc: jsPDF, rgb: [number, number, number]) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}
function setTextColor(doc: jsPDF, rgb: [number, number, number]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}
function setDrawColor(doc: jsPDF, rgb: [number, number, number]) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

/** Full-page dark background */
function drawPageBg(doc: jsPDF) {
  setFill(doc, COLORS.bg);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
}

/** Subtle grid lines */
function drawGrid(doc: jsPDF) {
  doc.setLineWidth(0.1);
  setDrawColor(doc, [10, 20, 40]);
  const step = 8;
  for (let x = 0; x <= PAGE_W; x += step) {
    doc.line(x, 0, x, PAGE_H);
  }
  for (let y = 0; y <= PAGE_H; y += step) {
    doc.line(0, y, PAGE_W, y);
  }
}

/** Page number + footer */
function drawFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const y = PAGE_H - 8;
  // Footer line
  doc.setLineWidth(0.3);
  setDrawColor(doc, COLORS.border);
  doc.line(MARGIN, y - 3, PAGE_W - MARGIN, y - 3);

  setTextColor(doc, COLORS.muted);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by AcousticSpace Deepfake Detection System  •  Infotact AI', MARGIN, y);
  doc.text(`Page ${pageNum} / ${totalPages}`, PAGE_W - MARGIN, y, { align: 'right' });
}

/** Section title bar */
function drawSectionTitle(doc: jsPDF, label: string, y: number, color = COLORS.cyan): number {
  // accent bar
  setFill(doc, color);
  doc.rect(MARGIN, y, 3, 5.5, 'F');
  // label
  setTextColor(doc, color);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(label.toUpperCase(), MARGIN + 6, y + 4);
  // divider line
  doc.setLineWidth(0.3);
  setDrawColor(doc, COLORS.border);
  doc.line(MARGIN + 6, y + 6, PAGE_W - MARGIN, y + 6);
  return y + 11;
}

/** Key-value row */
function drawKV(
  doc: jsPDF,
  label: string,
  value: string,
  y: number,
  col: number = MARGIN,
  width: number = CONTENT_W,
  valueColor = COLORS.white
): number {
  setTextColor(doc, COLORS.muted);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(label, col, y);

  setTextColor(doc, valueColor);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  // Right-align value within width
  const valX = col + width;
  doc.text(value || '—', valX, y, { align: 'right', maxWidth: width * 0.65 });
  return y + 6;
}

/** Rounded card background */
function drawCard(doc: jsPDF, x: number, y: number, w: number, h: number, borderColor = COLORS.border) {
  setFill(doc, COLORS.bgCard);
  doc.roundedRect(x, y, w, h, 2, 2, 'F');
  doc.setLineWidth(0.3);
  setDrawColor(doc, borderColor);
  doc.roundedRect(x, y, w, h, 2, 2, 'S');
}

/** Convert a remote image URL to base64 via fetch (with CORS) */
async function urlToBase64(url: string): Promise<string | null> {
  try {
    const res = await fetch(url, { mode: 'cors' });
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// ─── Main Export ──────────────────────────────────────────────────────────────
export async function generatePdfReport(
  result: PredictionResult,
  fileInfo: AudioFileInfo | null,
  settings: AppSettings,
  isReal: boolean,
  aiExplanation: string,
  riskLevel: string,
  getImageUrl: (path?: string) => string
): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true });
  const reportId = `AS-${Date.now().toString(36).toUpperCase()}`;
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  const accentRgb: [number, number, number] = isReal ? COLORS.green : COLORS.red;
  const modelVersion = `AASIST ${result.model_used || settings.modelVersion}`;

  // ── Pre-fetch all feature images ────────────────────────────────────────────
  const featureKeys = ['mel', 'mfcc', 'spectrogram', 'chroma', 'spectral_contrast', 'rir'] as const;
  const featureLabels: Record<string, string> = {
    mel: 'Mel Spectrogram',
    mfcc: 'MFCC Features',
    spectrogram: 'Spectrogram',
    chroma: 'Chroma Features',
    spectral_contrast: 'Spectral Contrast',
    rir: 'Room Impulse Response (RIR)',
  };

  const featureImages: Record<string, string | null> = {};
  await Promise.all(
    featureKeys.map(async (key) => {
      const path = result.features?.[key];
      if (path) {
        const url = getImageUrl(path);
        featureImages[key] = await urlToBase64(url);
      } else {
        featureImages[key] = null;
      }
    })
  );

  const hasAnyImage = Object.values(featureImages).some(Boolean);

  // Total pages estimate: cover(1) + details(1) + explanation(1) + features(1 or 2)
  const TOTAL_PAGES = hasAnyImage ? 4 : 3;

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 1 — COVER
  // ═══════════════════════════════════════════════════════════════════════════
  drawPageBg(doc);
  drawGrid(doc);

  // Top accent band
  setFill(doc, [6, 20, 50]);
  doc.rect(0, 0, PAGE_W, 6, 'F');
  setFill(doc, accentRgb);
  doc.rect(0, 0, PAGE_W, 1.5, 'F');

  // Large logo text
  let cy = 52;
  setTextColor(doc, COLORS.cyan);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('AcousticSpace', PAGE_W / 2, cy, { align: 'center' });
  cy += 10;

  setTextColor(doc, accentRgb);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Deepfake Audio Detection Report', PAGE_W / 2, cy, { align: 'center' });
  cy += 6;

  // Decorative cyan line
  setDrawColor(doc, COLORS.cyan);
  doc.setLineWidth(0.6);
  doc.line(PAGE_W / 2 - 30, cy, PAGE_W / 2 + 30, cy);
  cy += 12;

  // Prediction result badge
  const badgeW = 80;
  const badgeX = PAGE_W / 2 - badgeW / 2;
  setFill(doc, isReal ? [10, 40, 25] : [40, 10, 10]);
  doc.roundedRect(badgeX, cy, badgeW, 14, 3, 3, 'F');
  doc.setLineWidth(0.5);
  setDrawColor(doc, accentRgb);
  doc.roundedRect(badgeX, cy, badgeW, 14, 3, 3, 'S');
  setTextColor(doc, accentRgb);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(result.prediction, PAGE_W / 2, cy + 9, { align: 'center' });
  cy += 22;

  // Confidence big number
  doc.setFontSize(40);
  doc.setFont('helvetica', 'bold');
  setTextColor(doc, accentRgb);
  doc.text(`${result.confidence.toFixed(2)}%`, PAGE_W / 2, cy, { align: 'center' });
  cy += 5;
  setTextColor(doc, COLORS.muted);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Confidence Score', PAGE_W / 2, cy, { align: 'center' });
  cy += 20;

  // Meta card
  const cardH = 52;
  drawCard(doc, MARGIN, cy, CONTENT_W, cardH);
  let ky = cy + 9;
  const half = CONTENT_W / 2 - 4;

  // Left column
  drawKV(doc, 'Report ID', reportId, ky, MARGIN + 4, half, COLORS.cyan);
  ky += 7;
  drawKV(doc, 'Generated Date', dateStr, ky, MARGIN + 4, half);
  ky += 7;
  drawKV(doc, 'Generated Time', timeStr, ky, MARGIN + 4, half);

  // Right column
  ky = cy + 9;
  const rCol = MARGIN + half + 8;
  drawKV(doc, 'Model Version', modelVersion, ky, rCol, half, COLORS.purple);
  ky += 7;
  drawKV(doc, 'Risk Level', riskLevel, ky, rCol, half,
    riskLevel === 'LOW' ? COLORS.green : riskLevel === 'HIGH' ? COLORS.red : COLORS.amber);
  ky += 7;
  drawKV(doc, 'Platform', 'Infotact AcousticSpace', ky, rCol, half, COLORS.cyan);

  cy += cardH + 12;

  // Tagline
  setTextColor(doc, COLORS.muted);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'This report is generated by the AcousticSpace AI system and is intended for research and evaluation purposes.',
    PAGE_W / 2, cy, { align: 'center', maxWidth: CONTENT_W }
  );

  // Bottom accent
  setFill(doc, accentRgb);
  doc.rect(0, PAGE_H - 1.5, PAGE_W, 1.5, 'F');
  drawFooter(doc, 1, TOTAL_PAGES);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 2 — DETAILS
  // ═══════════════════════════════════════════════════════════════════════════
  doc.addPage();
  drawPageBg(doc);
  drawGrid(doc);
  setFill(doc, accentRgb);
  doc.rect(0, 0, PAGE_W, 1.5, 'F');

  let y = MARGIN + 4;

  // ── File Information ───────────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'File Information', y, COLORS.cyan);
  drawCard(doc, MARGIN, y, CONTENT_W, 38);
  let fy = y + 7;
  drawKV(doc, 'File Name', result.filename, fy, MARGIN + 4, CONTENT_W - 8);
  fy += 6.5;
  drawKV(doc, 'File Size', fileInfo?.size || '—', fy, MARGIN + 4, CONTENT_W - 8);
  fy += 6.5;
  drawKV(doc, 'Audio Duration', fileInfo?.duration || '—', fy, MARGIN + 4, CONTENT_W - 8);
  fy += 6.5;
  drawKV(doc, 'Processing Time', result.processing_time, fy, MARGIN + 4, CONTENT_W - 8);
  fy += 6.5;
  drawKV(doc, 'Timestamp', result.timestamp ? new Date(result.timestamp).toLocaleString() : '—', fy, MARGIN + 4, CONTENT_W - 8);
  y += 44;

  // ── Prediction Summary ─────────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'Prediction Summary', y, accentRgb);
  const halfW = (CONTENT_W - 4) / 2;

  // Left: prediction card
  drawCard(doc, MARGIN, y, halfW, 52, accentRgb);
  setTextColor(doc, accentRgb);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.text('PREDICTION', MARGIN + 4, y + 8);
  doc.setFontSize(11);
  const predLines = doc.splitTextToSize(result.prediction, halfW - 8);
  doc.text(predLines, MARGIN + 4, y + 16);

  setTextColor(doc, COLORS.muted);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('CONFIDENCE', MARGIN + 4, y + 32);
  setTextColor(doc, COLORS.cyan);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`${result.confidence.toFixed(2)}%`, MARGIN + 4, y + 41);

  // Right: details grid (2×2)
  const rc = MARGIN + halfW + 4;
  const miniW = halfW / 2 - 2;
  const items = [
    { label: 'RISK LEVEL', value: riskLevel, color: riskLevel === 'LOW' ? COLORS.green : riskLevel === 'HIGH' ? COLORS.red : COLORS.amber },
    { label: 'MODEL', value: modelVersion, color: COLORS.purple },
    { label: 'INFERENCE', value: result.inference_time || result.processing_time || '—', color: COLORS.amber },
    { label: 'SAMPLE RATE', value: fileInfo?.sampleRate || '16000 Hz', color: COLORS.blue },
  ];
  items.forEach((item, idx) => {
    const mx = rc + (idx % 2) * (miniW + 2);
    const my = y + Math.floor(idx / 2) * 27;
    drawCard(doc, mx, my, miniW, 24, item.color);
    setTextColor(doc, COLORS.muted);
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.text(item.label, mx + 3, my + 7);
    setTextColor(doc, item.color);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const vLines = doc.splitTextToSize(item.value, miniW - 6);
    doc.text(vLines, mx + 3, my + 15);
  });
  y += 58;

  // ── Breathing Analysis ─────────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'Breathing Analysis', y, COLORS.blue);
  if (result.breathing) {
    const breathStatus = result.breathing.breathing_status;
    const breathColor: [number, number, number] =
      breathStatus === 'Very Stable' || breathStatus === 'Stable' ? COLORS.green
      : breathStatus === 'Moderately Variable' ? COLORS.amber
      : COLORS.red;

    drawCard(doc, MARGIN, y, CONTENT_W, 42);
    let by = y + 7;
    drawKV(doc, 'Breathing Status', breathStatus || '—', by, MARGIN + 4, CONTENT_W - 8, breathColor);
    by += 6.5;
    drawKV(doc, 'Breath Score', String(result.breathing.breath_score ?? '—'), by, MARGIN + 4, CONTENT_W - 8, COLORS.cyan);
    by += 6.5;
    // Analysis text (multiline)
    setTextColor(doc, COLORS.muted);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.text('Analysis', MARGIN + 4, by);
    setTextColor(doc, COLORS.secondary);
    doc.setFontSize(8);
    const analysisLines = doc.splitTextToSize(result.breathing.analysis || '—', CONTENT_W - 16);
    doc.text(analysisLines, MARGIN + 4, by + 5.5);
    y += 45;

    // Breathing Details
    if (result.breathing.details) {
      y = drawSectionTitle(doc, 'Breathing Details', y, COLORS.cyan);
      const dItems = [
        { label: 'RMS Variation', value: result.breathing.details.rms_variation?.toFixed(4) ?? '—', color: COLORS.cyan },
        { label: 'Zero Crossing Rate', value: result.breathing.details.zero_crossing_rate?.toFixed(4) ?? '—', color: COLORS.purple },
        { label: 'Spectral Variation', value: result.breathing.details.spectral_variation?.toFixed(4) ?? '—', color: COLORS.amber },
        { label: 'Silence Ratio', value: result.breathing.details.silence_ratio?.toFixed(4) ?? '—', color: COLORS.green },
      ];
      const dW = (CONTENT_W - 6) / 4;
      drawCard(doc, MARGIN, y, CONTENT_W, 30);
      dItems.forEach((d, i) => {
        const dx = MARGIN + 3 + i * (dW + 2);
        setTextColor(doc, COLORS.muted);
        doc.setFontSize(6.5);
        doc.setFont('helvetica', 'normal');
        doc.text(d.label.toUpperCase(), dx, y + 9);
        setTextColor(doc, d.color);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(d.value, dx, y + 20);
      });
      y += 36;
    }
  } else {
    drawCard(doc, MARGIN, y, CONTENT_W, 14);
    setTextColor(doc, COLORS.muted);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text('Breathing analysis data not available.', MARGIN + 4, y + 9);
    y += 20;
  }

  // ── AI Explanation ─────────────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'AI Explanation', y, COLORS.cyan);
  const explLines = doc.splitTextToSize(aiExplanation, CONTENT_W - 12);
  const explH = explLines.length * 5.5 + 12;
  drawCard(doc, MARGIN, y, CONTENT_W, explH, accentRgb);
  // Accent sidebar
  setFill(doc, accentRgb);
  doc.rect(MARGIN + 2, y + 4, 2.5, explH - 8, 'F');
  setTextColor(doc, COLORS.secondary);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text(explLines, MARGIN + 9, y + 9);
  y += explH + 6;

  // ── Summary / Conclusion ───────────────────────────────────────────────────
  y = drawSectionTitle(doc, 'Summary', y, COLORS.purple);
  const summaryText =
    `The uploaded recording was analysed using the ${modelVersion} deepfake detection model together with supplementary acoustic feature extraction. ` +
    `The final prediction is based solely on the AASIST model, while the breathing analysis provides additional acoustic insights. ` +
    `This report documents all extracted features and analysis results for evaluation and research purposes.`;
  const sumLines = doc.splitTextToSize(summaryText, CONTENT_W - 12);
  const sumH = sumLines.length * 5.5 + 12;
  drawCard(doc, MARGIN, y, CONTENT_W, sumH);
  setTextColor(doc, COLORS.secondary);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text(sumLines, MARGIN + 4, y + 9);

  drawFooter(doc, 2, TOTAL_PAGES);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 3+ — ACOUSTIC FEATURE IMAGES
  // ═══════════════════════════════════════════════════════════════════════════
  if (hasAnyImage) {
    doc.addPage();
    drawPageBg(doc);
    drawGrid(doc);
    setFill(doc, accentRgb);
    doc.rect(0, 0, PAGE_W, 1.5, 'F');

    let iy = MARGIN + 4;
    iy = drawSectionTitle(doc, 'Acoustic Feature Images', iy, COLORS.cyan);

    // 2-column grid
    const colW = (CONTENT_W - 6) / 2;
    const imgH = 52; // height of each image cell
    const cellH = imgH + 20; // image + label area

    let pageCount = 3;
    let imgIdx = 0;

    for (const key of featureKeys) {
      const b64 = featureImages[key];
      const label = featureLabels[key];
      const desc = FEATURE_DESCRIPTIONS[key] || '';
      const col = imgIdx % 2;
      const row = Math.floor(imgIdx / 2);
      const cx = MARGIN + col * (colW + 6);
      const cy2 = iy + row * (cellH + 6);

      // Check if we need a new page (3 rows = 6 images fit, but safe for overflow)
      if (cy2 + cellH > PAGE_H - 20 && imgIdx > 0) {
        drawFooter(doc, pageCount, TOTAL_PAGES + 1);
        doc.addPage();
        drawPageBg(doc);
        drawGrid(doc);
        setFill(doc, accentRgb);
        doc.rect(0, 0, PAGE_W, 1.5, 'F');
        iy = MARGIN + 4;
        pageCount++;
        imgIdx = 0;
      }

      const cyCell = iy + Math.floor(imgIdx / 2) * (cellH + 6);

      // Cell card
      drawCard(doc, cx, cyCell, colW, cellH, COLORS.border);

      if (b64) {
        // Image
        const imgFormat = b64.startsWith('data:image/png') ? 'PNG' : 'JPEG';
        doc.addImage(b64, imgFormat, cx + 2, cyCell + 2, colW - 4, imgH - 2, undefined, 'FAST');
      } else {
        // Placeholder
        setFill(doc, [10, 20, 40]);
        doc.rect(cx + 2, cyCell + 2, colW - 4, imgH - 2, 'F');
        setTextColor(doc, COLORS.muted);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.text('Image not available', cx + colW / 2, cyCell + imgH / 2, { align: 'center' });
      }

      // Label area
      const labelY = cyCell + imgH + 2;
      setTextColor(doc, COLORS.white);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.text(label, cx + 3, labelY + 5);
      setTextColor(doc, COLORS.muted);
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'normal');
      const descLines = doc.splitTextToSize(desc, colW - 6);
      doc.text(descLines.slice(0, 2), cx + 3, labelY + 10.5);

      imgIdx++;
    }

    drawFooter(doc, pageCount, TOTAL_PAGES);
  }

  // ── Save ────────────────────────────────────────────────────────────────────
  const safeFilename = result.filename.replace(/[^a-zA-Z0-9_\-]/g, '_');
  doc.save(`AcousticSpace_Report_${safeFilename}_${reportId}.pdf`);
}
